using MortgageMarketAnalysisAgent.Models.Documents;
using MortgageMarketAnalysisAgent.Models.Documents.Components;
using MortgageMarketAnalysisAgent.Models.RentCast;
using MortgageMarketAnalysisAgent.Services.Interfaces;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Text;

namespace MortgageMarketAnalysisAgent.Clients;

public class RentCastClient : IMarketAnalyzer
{
    private readonly IReportBuildingService _reportBuildingService;

    const string TARGET_PROPERTY_TYPE = "Single Family";
    const string SUBJECT_ROLE = "SubjectBedroomBucket";
    const string ADJACENT_ROLE = "AdjacentBedroomAnchor";
    const string ANCHOR_NEXT_HIGHER = "NextHigherBedroomBucket";

    public RentCastClient(IReportBuildingService reportBuildingService)
    {
        _reportBuildingService = reportBuildingService;
    }

    public async Task<IMarketValue> AnalyzeMarket(string zipcode)
    {
        var houses = await _reportBuildingService.BuildMarketHouseReport();

        var trends = JsonConvert.DeserializeObject<RentCast>(marketTrends)!;

        return await Task.FromResult(trends);
    }


    public static List<MarketTrend> BuildRentCastDataSource(HousingMarketModel house, RentCast trends)
    {
        List<MarketTrend> marketTrends = new List<MarketTrend>();

        var bedroomData = trends.saleData.dataByBedrooms
                                       .Where(p =>
                                              (p.bedrooms.Equals(house.BedRooms) &&
                                              p.minSquareFootage <= house.SquareFootage &&
                                              p.maxSquareFootage >= house.SquareFootage || p.bedrooms.Equals(house.BedRooms + 1)))
                                       .ToList();
        var propTypData = trends.saleData.dataByPropertyType
                                        .FirstOrDefault(p => p.propertyType.Equals(TARGET_PROPERTY_TYPE));


        marketTrends.Add(new MarketTrend
        {
            Source = nameof(RentCast),
            ZipCode = trends.zipCode,
            LastUpdated = trends.saleData.lastUpdatedDate,
            PropertyTypeMarketData = bedroomData.Where(p => p.bedrooms.Equals(house.BedRooms))
                                                .Select(p => new PropertyTypeMarketData
                                                {
                                                    PropertyType = TARGET_PROPERTY_TYPE,
                                                    MedianPrice = p.medianPrice,
                                                    MedianPricePerSquareFoot = p.medianPricePerSquareFoot,
                                                    MedianSquareFootage = p.medianSquareFootage,
                                                    TotalListings = p.totalListings,
                                                    MedianDaysOnMarket = p.medianDaysOnMarket
                                                }).ToList(),
            BedroomMarketData = bedroomData.Select(p => new BedroomMarketData
            {
                Role = p.bedrooms == house.BedRooms ? SUBJECT_ROLE : ADJACENT_ROLE,
                AnchorDirection = p.bedrooms > house.BedRooms ? ANCHOR_NEXT_HIGHER : null,
                BedRooms = p.bedrooms,
                BathRooms = house.BathRooms,
                MedianPrice = p.medianPrice,
                MedianPricePerSquareFoot = p.medianPricePerSquareFoot,
                MedianSquareFootage = p.medianSquareFootage,
                TotalListings = p.totalListings,
                MedianDaysOnMarket = p.medianDaysOnMarket,
                PropertyType = TARGET_PROPERTY_TYPE,
                PropertyTypeMedian = propTypData.medianPrice,
                propertyTypeMedianPricePerSquareFoot = propTypData.medianPricePerSquareFoot
            }).ToList()
        });

        return marketTrends;
    }

    #region Fake Data
    string marketTrends = @"{
  ""id"": ""76227"",
  ""zipCode"": ""76227"",
  ""saleData"": {
    ""lastUpdatedDate"": ""2026-06-06T00:00:00.000Z"",
    ""averagePrice"": 508161,
    ""medianPrice"": 384990,
    ""minPrice"": 61000,
    ""maxPrice"": 8235000,
    ""averagePricePerSquareFoot"": 191.89,
    ""medianPricePerSquareFoot"": 183.89,
    ""minPricePerSquareFoot"": 99.88,
    ""maxPricePerSquareFoot"": 2315.16,
    ""averageSquareFootage"": 2342,
    ""medianSquareFootage"": 2186,
    ""minSquareFootage"": 720,
    ""maxSquareFootage"": 6595,
    ""averageDaysOnMarket"": 60.11,
    ""medianDaysOnMarket"": 36,
    ""minDaysOnMarket"": 1,
    ""maxDaysOnMarket"": 365,
    ""newListings"": 100,
    ""totalListings"": 1513,
    ""dataByPropertyType"": [
      {
        ""propertyType"": ""Land"",
        ""averagePrice"": 1836974,
        ""medianPrice"": 1375000,
        ""minPrice"": 61000,
        ""maxPrice"": 8235000,
        ""averagePricePerSquareFoot"": null,
        ""medianPricePerSquareFoot"": null,
        ""minPricePerSquareFoot"": null,
        ""maxPricePerSquareFoot"": null,
        ""averageSquareFootage"": null,
        ""medianSquareFootage"": null,
        ""minSquareFootage"": null,
        ""maxSquareFootage"": null,
        ""averageDaysOnMarket"": 134.36,
        ""medianDaysOnMarket"": 95,
        ""minDaysOnMarket"": 2,
        ""maxDaysOnMarket"": 356,
        ""newListings"": 1,
        ""totalListings"": 59
      },
      {
        ""propertyType"": ""Manufactured"",
        ""averagePrice"": 4815525,
        ""medianPrice"": 4815525,
        ""minPrice"": 4815525,
        ""maxPrice"": 4815525,
        ""averagePricePerSquareFoot"": 2315.16,
        ""medianPricePerSquareFoot"": 2315.16,
        ""minPricePerSquareFoot"": 2315.16,
        ""maxPricePerSquareFoot"": 2315.16,
        ""averageSquareFootage"": 2080,
        ""medianSquareFootage"": 2080,
        ""minSquareFootage"": 2080,
        ""maxSquareFootage"": 2080,
        ""averageDaysOnMarket"": 235,
        ""medianDaysOnMarket"": 235,
        ""minDaysOnMarket"": 235,
        ""maxDaysOnMarket"": 235,
        ""newListings"": 0,
        ""totalListings"": 1
      },
      {
        ""propertyType"": ""Multi-Family"",
        ""averagePrice"": 430000,
        ""medianPrice"": 430000,
        ""minPrice"": 430000,
        ""maxPrice"": 430000,
        ""averagePricePerSquareFoot"": 204.37,
        ""medianPricePerSquareFoot"": 204.37,
        ""minPricePerSquareFoot"": 204.37,
        ""maxPricePerSquareFoot"": 204.37,
        ""averageSquareFootage"": 2104,
        ""medianSquareFootage"": 2104,
        ""minSquareFootage"": 2104,
        ""maxSquareFootage"": 2104,
        ""averageDaysOnMarket"": 29,
        ""medianDaysOnMarket"": 29,
        ""minDaysOnMarket"": 29,
        ""maxDaysOnMarket"": 29,
        ""newListings"": 0,
        ""totalListings"": 1
      },
      {
        ""propertyType"": ""Single Family"",
        ""averagePrice"": 452882,
        ""medianPrice"": 383990,
        ""minPrice"": 159000,
        ""maxPrice"": 5890000,
        ""averagePricePerSquareFoot"": 190.41,
        ""medianPricePerSquareFoot"": 183.73,
        ""minPricePerSquareFoot"": 99.88,
        ""maxPricePerSquareFoot"": 1370.72,
        ""averageSquareFootage"": 2351,
        ""medianSquareFootage"": 2206,
        ""minSquareFootage"": 720,
        ""maxSquareFootage"": 6595,
        ""averageDaysOnMarket"": 57.55,
        ""medianDaysOnMarket"": 36,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 365,
        ""newListings"": 99,
        ""totalListings"": 1434
      },
      {
        ""propertyType"": ""Townhouse"",
        ""averagePrice"": 321550,
        ""medianPrice"": 320000,
        ""minPrice"": 296000,
        ""maxPrice"": 340000,
        ""averagePricePerSquareFoot"": 191.54,
        ""medianPricePerSquareFoot"": 192.64,
        ""minPricePerSquareFoot"": 172.8,
        ""maxPricePerSquareFoot"": 203.54,
        ""averageSquareFootage"": 1680,
        ""medianSquareFootage"": 1713,
        ""minSquareFootage"": 1582,
        ""maxSquareFootage"": 1746,
        ""averageDaysOnMarket"": 36.67,
        ""medianDaysOnMarket"": 37,
        ""minDaysOnMarket"": 30,
        ""maxDaysOnMarket"": 46,
        ""newListings"": 0,
        ""totalListings"": 18
      }
    ],
    ""dataByBedrooms"": [
      {
        ""bedrooms"": 1,
        ""averagePrice"": 888000,
        ""medianPrice"": 888000,
        ""minPrice"": 888000,
        ""maxPrice"": 888000,
        ""averagePricePerSquareFoot"": 911.7,
        ""medianPricePerSquareFoot"": 911.7,
        ""minPricePerSquareFoot"": 911.7,
        ""maxPricePerSquareFoot"": 911.7,
        ""averageSquareFootage"": 974,
        ""medianSquareFootage"": 974,
        ""minSquareFootage"": 974,
        ""maxSquareFootage"": 974,
        ""averageDaysOnMarket"": 225,
        ""medianDaysOnMarket"": 225,
        ""minDaysOnMarket"": 225,
        ""maxDaysOnMarket"": 225,
        ""newListings"": 0,
        ""totalListings"": 1
      },
      {
        ""bedrooms"": 2,
        ""averagePrice"": 350532,
        ""medianPrice"": 339000,
        ""minPrice"": 159000,
        ""maxPrice"": 599000,
        ""averagePricePerSquareFoot"": 212.25,
        ""medianPricePerSquareFoot"": 204.37,
        ""minPricePerSquareFoot"": 112.1,
        ""maxPricePerSquareFoot"": 343.75,
        ""averageSquareFootage"": 1691,
        ""medianSquareFootage"": 1591,
        ""minSquareFootage"": 720,
        ""maxSquareFootage"": 2917,
        ""averageDaysOnMarket"": 74.68,
        ""medianDaysOnMarket"": 53,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 247,
        ""newListings"": 0,
        ""totalListings"": 31
      },
      {
        ""bedrooms"": 3,
        ""averagePrice"": 352168,
        ""medianPrice"": 320000,
        ""minPrice"": 165000,
        ""maxPrice"": 4815525,
        ""averagePricePerSquareFoot"": 199.39,
        ""medianPricePerSquareFoot"": 192.64,
        ""minPricePerSquareFoot"": 103.33,
        ""maxPricePerSquareFoot"": 2315.16,
        ""averageSquareFootage"": 1767,
        ""medianSquareFootage"": 1687,
        ""minSquareFootage"": 1032,
        ""maxSquareFootage"": 3886,
        ""averageDaysOnMarket"": 56.07,
        ""medianDaysOnMarket"": 36,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 365,
        ""newListings"": 35,
        ""totalListings"": 503
      },
      {
        ""bedrooms"": 4,
        ""averagePrice"": 486827,
        ""medianPrice"": 409990,
        ""minPrice"": 244999,
        ""maxPrice"": 5890000,
        ""averagePricePerSquareFoot"": 186.79,
        ""medianPricePerSquareFoot"": 177.38,
        ""minPricePerSquareFoot"": 99.88,
        ""maxPricePerSquareFoot"": 1370.72,
        ""averageSquareFootage"": 2539,
        ""medianSquareFootage"": 2426,
        ""minSquareFootage"": 1461,
        ""maxSquareFootage"": 6595,
        ""averageDaysOnMarket"": 57.3,
        ""medianDaysOnMarket"": 32,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 353,
        ""newListings"": 54,
        ""totalListings"": 780
      },
      {
        ""bedrooms"": 5,
        ""averagePrice"": 656061,
        ""medianPrice"": 574000,
        ""minPrice"": 309900,
        ""maxPrice"": 4800000,
        ""averagePricePerSquareFoot"": 184,
        ""medianPricePerSquareFoot"": 168.56,
        ""minPricePerSquareFoot"": 100.12,
        ""maxPricePerSquareFoot"": 851.21,
        ""averageSquareFootage"": 3440,
        ""medianSquareFootage"": 3382,
        ""minSquareFootage"": 2152,
        ""maxSquareFootage"": 5712,
        ""averageDaysOnMarket"": 56.53,
        ""medianDaysOnMarket"": 33,
        ""minDaysOnMarket"": 2,
        ""maxDaysOnMarket"": 364,
        ""newListings"": 10,
        ""totalListings"": 134
      },
      {
        ""bedrooms"": 6,
        ""averagePrice"": 786798,
        ""medianPrice"": 725000,
        ""minPrice"": 400000,
        ""maxPrice"": 1435000,
        ""averagePricePerSquareFoot"": 173.56,
        ""medianPricePerSquareFoot"": 163.73,
        ""minPricePerSquareFoot"": 122.7,
        ""maxPricePerSquareFoot"": 253.18,
        ""averageSquareFootage"": 4358,
        ""medianSquareFootage"": 4403,
        ""minSquareFootage"": 3260,
        ""maxSquareFootage"": 5668,
        ""averageDaysOnMarket"": 85.8,
        ""medianDaysOnMarket"": 63,
        ""minDaysOnMarket"": 36,
        ""maxDaysOnMarket"": 146,
        ""newListings"": 0,
        ""totalListings"": 5
      }
    ],
    ""history"": {
      ""2026-01"": {
        ""date"": ""2026-01-01T00:00:00.000Z"",
        ""averagePrice"": 499697,
        ""medianPrice"": 375000,
        ""minPrice"": 99900,
        ""maxPrice"": 7000000,
        ""averagePricePerSquareFoot"": 192.45,
        ""medianPricePerSquareFoot"": 181.52,
        ""minPricePerSquareFoot"": 103.97,
        ""maxPricePerSquareFoot"": 2315.16,
        ""averageSquareFootage"": 2325,
        ""medianSquareFootage"": 2210,
        ""minSquareFootage"": 768,
        ""maxSquareFootage"": 6595,
        ""averageDaysOnMarket"": 65.16,
        ""medianDaysOnMarket"": 37,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 364,
        ""newListings"": 474,
        ""totalListings"": 1251,
        ""dataByPropertyType"": [
          {
            ""propertyType"": ""Land"",
            ""averagePrice"": 1716568,
            ""medianPrice"": 1150000,
            ""minPrice"": 99900,
            ""maxPrice"": 7000000,
            ""averagePricePerSquareFoot"": null,
            ""medianPricePerSquareFoot"": null,
            ""minPricePerSquareFoot"": null,
            ""maxPricePerSquareFoot"": null,
            ""averageSquareFootage"": null,
            ""medianSquareFootage"": null,
            ""minSquareFootage"": null,
            ""maxSquareFootage"": null,
            ""averageDaysOnMarket"": 157.57,
            ""medianDaysOnMarket"": 130,
            ""minDaysOnMarket"": 23,
            ""maxDaysOnMarket"": 352,
            ""newListings"": 0,
            ""totalListings"": 45
          },
          {
            ""propertyType"": ""Single Family"",
            ""averagePrice"": 454414,
            ""medianPrice"": 374999,
            ""minPrice"": 175000,
            ""maxPrice"": 5675000,
            ""averagePricePerSquareFoot"": 192.46,
            ""medianPricePerSquareFoot"": 181.52,
            ""minPricePerSquareFoot"": 103.97,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 2325,
            ""medianSquareFootage"": 2210,
            ""minSquareFootage"": 768,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 62.09,
            ""medianDaysOnMarket"": 32,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 364,
            ""newListings"": 474,
            ""totalListings"": 1205
          },
          {
            ""propertyType"": ""Townhouse"",
            ""averagePrice"": 305900,
            ""medianPrice"": 305900,
            ""minPrice"": 305900,
            ""maxPrice"": 305900,
            ""averagePricePerSquareFoot"": 170.13,
            ""medianPricePerSquareFoot"": 170.13,
            ""minPricePerSquareFoot"": 170.13,
            ""maxPricePerSquareFoot"": 170.13,
            ""averageSquareFootage"": 1798,
            ""medianSquareFootage"": 1798,
            ""minSquareFootage"": 1798,
            ""maxSquareFootage"": 1798,
            ""averageDaysOnMarket"": 50,
            ""medianDaysOnMarket"": 50,
            ""minDaysOnMarket"": 50,
            ""maxDaysOnMarket"": 50,
            ""newListings"": 0,
            ""totalListings"": 1
          }
        ],
        ""dataByBedrooms"": [
          {
            ""bedrooms"": 2,
            ""averagePrice"": 316650,
            ""medianPrice"": 300000,
            ""minPrice"": 175000,
            ""maxPrice"": 630000,
            ""averagePricePerSquareFoot"": 231.58,
            ""medianPricePerSquareFoot"": 211.41,
            ""minPricePerSquareFoot"": 177.65,
            ""maxPricePerSquareFoot"": 343.75,
            ""averageSquareFootage"": 1402,
            ""medianSquareFootage"": 1471,
            ""minSquareFootage"": 768,
            ""maxSquareFootage"": 2609,
            ""averageDaysOnMarket"": 89.19,
            ""medianDaysOnMarket"": 100,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 217,
            ""newListings"": 6,
            ""totalListings"": 22
          },
          {
            ""bedrooms"": 3,
            ""averagePrice"": 356863,
            ""medianPrice"": 314900,
            ""minPrice"": 199900,
            ""maxPrice"": 4990000,
            ""averagePricePerSquareFoot"": 202.39,
            ""medianPricePerSquareFoot"": 188.6,
            ""minPricePerSquareFoot"": 130.19,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 1740,
            ""medianSquareFootage"": 1644,
            ""minSquareFootage"": 874,
            ""maxSquareFootage"": 3886,
            ""averageDaysOnMarket"": 61.98,
            ""medianDaysOnMarket"": 29,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 364,
            ""newListings"": 157,
            ""totalListings"": 431
          },
          {
            ""bedrooms"": 4,
            ""averagePrice"": 486609,
            ""medianPrice"": 417000,
            ""minPrice"": 205899,
            ""maxPrice"": 5675000,
            ""averagePricePerSquareFoot"": 185.31,
            ""medianPricePerSquareFoot"": 175.85,
            ""minPricePerSquareFoot"": 103.97,
            ""maxPricePerSquareFoot"": 1751.87,
            ""averageSquareFootage"": 2560,
            ""medianSquareFootage"": 2465,
            ""minSquareFootage"": 1535,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 60.69,
            ""medianDaysOnMarket"": 30,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 313,
            ""newListings"": 266,
            ""totalListings"": 636
          },
          {
            ""bedrooms"": 5,
            ""averagePrice"": 656077,
            ""medianPrice"": 549500,
            ""minPrice"": 284280,
            ""maxPrice"": 4800000,
            ""averagePricePerSquareFoot"": 187.23,
            ""medianPricePerSquareFoot"": 171.09,
            ""minPricePerSquareFoot"": 107.56,
            ""maxPricePerSquareFoot"": 851.21,
            ""averageSquareFootage"": 3339,
            ""medianSquareFootage"": 3266,
            ""minSquareFootage"": 1766,
            ""maxSquareFootage"": 6203,
            ""averageDaysOnMarket"": 63.74,
            ""medianDaysOnMarket"": 39,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 284,
            ""newListings"": 45,
            ""totalListings"": 114
          },
          {
            ""bedrooms"": 6,
            ""averagePrice"": 941667,
            ""medianPrice"": 950000,
            ""minPrice"": 425000,
            ""maxPrice"": 1450000,
            ""averagePricePerSquareFoot"": 188.63,
            ""medianPricePerSquareFoot"": 179.69,
            ""minPricePerSquareFoot"": 130.37,
            ""maxPricePerSquareFoot"": 255.82,
            ""averageSquareFootage"": 4738,
            ""medianSquareFootage"": 5287,
            ""minSquareFootage"": 3260,
            ""maxSquareFootage"": 5668,
            ""averageDaysOnMarket"": 115.67,
            ""medianDaysOnMarket"": 45,
            ""minDaysOnMarket"": 43,
            ""maxDaysOnMarket"": 259,
            ""newListings"": 0,
            ""totalListings"": 3
          }
        ]
      },
      ""2026-02"": {
        ""date"": ""2026-02-01T00:00:00.000Z"",
        ""averagePrice"": 483944,
        ""medianPrice"": 375000,
        ""minPrice"": 75000,
        ""maxPrice"": 7000000,
        ""averagePricePerSquareFoot"": 190.29,
        ""medianPricePerSquareFoot"": 179.79,
        ""minPricePerSquareFoot"": 102.15,
        ""maxPricePerSquareFoot"": 2315.16,
        ""averageSquareFootage"": 2300,
        ""medianSquareFootage"": 2181,
        ""minSquareFootage"": 768,
        ""maxSquareFootage"": 6595,
        ""averageDaysOnMarket"": 63.14,
        ""medianDaysOnMarket"": 33,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 340,
        ""newListings"": 425,
        ""totalListings"": 1285,
        ""dataByPropertyType"": [
          {
            ""propertyType"": ""Land"",
            ""averagePrice"": 1610282,
            ""medianPrice"": 1025000,
            ""minPrice"": 75000,
            ""maxPrice"": 7000000,
            ""averagePricePerSquareFoot"": null,
            ""medianPricePerSquareFoot"": null,
            ""minPricePerSquareFoot"": null,
            ""maxPricePerSquareFoot"": null,
            ""averageSquareFootage"": null,
            ""medianSquareFootage"": null,
            ""minSquareFootage"": null,
            ""maxSquareFootage"": null,
            ""averageDaysOnMarket"": 144.19,
            ""medianDaysOnMarket"": 133,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 313,
            ""newListings"": 9,
            ""totalListings"": 48
          },
          {
            ""propertyType"": ""Multi-Family"",
            ""averagePrice"": 1149000,
            ""medianPrice"": 1149000,
            ""minPrice"": 1149000,
            ""maxPrice"": 1149000,
            ""averagePricePerSquareFoot"": 215.37,
            ""medianPricePerSquareFoot"": 215.37,
            ""minPricePerSquareFoot"": 215.37,
            ""maxPricePerSquareFoot"": 215.37,
            ""averageSquareFootage"": 5335,
            ""medianSquareFootage"": 5335,
            ""minSquareFootage"": 5335,
            ""maxSquareFootage"": 5335,
            ""averageDaysOnMarket"": 134,
            ""medianDaysOnMarket"": 134,
            ""minDaysOnMarket"": 134,
            ""maxDaysOnMarket"": 134,
            ""newListings"": 0,
            ""totalListings"": 1
          },
          {
            ""propertyType"": ""Single Family"",
            ""averagePrice"": 439665,
            ""medianPrice"": 373990,
            ""minPrice"": 169000,
            ""maxPrice"": 4990000,
            ""averagePricePerSquareFoot"": 190.27,
            ""medianPricePerSquareFoot"": 179.77,
            ""minPricePerSquareFoot"": 102.15,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 2297,
            ""medianSquareFootage"": 2174,
            ""minSquareFootage"": 768,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 60.31,
            ""medianDaysOnMarket"": 31,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 340,
            ""newListings"": 416,
            ""totalListings"": 1236
          }
        ],
        ""dataByBedrooms"": [
          {
            ""bedrooms"": 1,
            ""averagePrice"": 948888,
            ""medianPrice"": 948888,
            ""minPrice"": 948888,
            ""maxPrice"": 948888,
            ""averagePricePerSquareFoot"": 974.22,
            ""medianPricePerSquareFoot"": 974.22,
            ""minPricePerSquareFoot"": 974.22,
            ""maxPricePerSquareFoot"": 974.22,
            ""averageSquareFootage"": 974,
            ""medianSquareFootage"": 974,
            ""minSquareFootage"": 974,
            ""maxSquareFootage"": 974,
            ""averageDaysOnMarket"": 127,
            ""medianDaysOnMarket"": 127,
            ""minDaysOnMarket"": 127,
            ""maxDaysOnMarket"": 127,
            ""newListings"": 0,
            ""totalListings"": 1
          },
          {
            ""bedrooms"": 2,
            ""averagePrice"": 333942,
            ""medianPrice"": 305000,
            ""minPrice"": 169000,
            ""maxPrice"": 635000,
            ""averagePricePerSquareFoot"": 230.78,
            ""medianPricePerSquareFoot"": 218.15,
            ""minPricePerSquareFoot"": 193.1,
            ""maxPricePerSquareFoot"": 343.75,
            ""averageSquareFootage"": 1481,
            ""medianSquareFootage"": 1551,
            ""minSquareFootage"": 768,
            ""maxSquareFootage"": 2609,
            ""averageDaysOnMarket"": 72.83,
            ""medianDaysOnMarket"": 46,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 245,
            ""newListings"": 6,
            ""totalListings"": 24
          },
          {
            ""bedrooms"": 3,
            ""averagePrice"": 351843,
            ""medianPrice"": 309990,
            ""minPrice"": 189000,
            ""maxPrice"": 4990000,
            ""averagePricePerSquareFoot"": 201.49,
            ""medianPricePerSquareFoot"": 188.27,
            ""minPricePerSquareFoot"": 130.19,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 1727,
            ""medianSquareFootage"": 1633,
            ""minSquareFootage"": 874,
            ""maxSquareFootage"": 3886,
            ""averageDaysOnMarket"": 58.57,
            ""medianDaysOnMarket"": 29,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 340,
            ""newListings"": 147,
            ""totalListings"": 443
          },
          {
            ""bedrooms"": 4,
            ""averagePrice"": 465469,
            ""medianPrice"": 409990,
            ""minPrice"": 205899,
            ""maxPrice"": 2850000,
            ""averagePricePerSquareFoot"": 180.95,
            ""medianPricePerSquareFoot"": 173.75,
            ""minPricePerSquareFoot"": 102.15,
            ""maxPricePerSquareFoot"": 724.45,
            ""averageSquareFootage"": 2531,
            ""medianSquareFootage"": 2404,
            ""minSquareFootage"": 1461,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 59.62,
            ""medianDaysOnMarket"": 33,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 332,
            ""newListings"": 223,
            ""totalListings"": 657
          },
          {
            ""bedrooms"": 5,
            ""averagePrice"": 647548,
            ""medianPrice"": 549500,
            ""minPrice"": 284280,
            ""maxPrice"": 4800000,
            ""averagePricePerSquareFoot"": 185.1,
            ""medianPricePerSquareFoot"": 167.23,
            ""minPricePerSquareFoot"": 107.56,
            ""maxPricePerSquareFoot"": 851.21,
            ""averageSquareFootage"": 3328,
            ""medianSquareFootage"": 3262,
            ""minSquareFootage"": 1766,
            ""maxSquareFootage"": 6203,
            ""averageDaysOnMarket"": 66.65,
            ""medianDaysOnMarket"": 36,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 296,
            ""newListings"": 39,
            ""totalListings"": 107
          },
          {
            ""bedrooms"": 6,
            ""averagePrice"": 928780,
            ""medianPrice"": 950000,
            ""minPrice"": 425000,
            ""maxPrice"": 1435000,
            ""averagePricePerSquareFoot"": 186.84,
            ""medianPricePerSquareFoot"": 179.69,
            ""minPricePerSquareFoot"": 130.37,
            ""maxPricePerSquareFoot"": 253.18,
            ""averageSquareFootage"": 4790,
            ""medianSquareFootage"": 5287,
            ""minSquareFootage"": 3260,
            ""maxSquareFootage"": 5668,
            ""averageDaysOnMarket"": 110.4,
            ""medianDaysOnMarket"": 73,
            ""minDaysOnMarket"": 5,
            ""maxDaysOnMarket"": 269,
            ""newListings"": 1,
            ""totalListings"": 5
          }
        ]
      },
      ""2026-03"": {
        ""date"": ""2026-03-01T00:00:00.000Z"",
        ""averagePrice"": 468314,
        ""medianPrice"": 380000,
        ""minPrice"": 75000,
        ""maxPrice"": 5400000,
        ""averagePricePerSquareFoot"": 189.24,
        ""medianPricePerSquareFoot"": 182.28,
        ""minPricePerSquareFoot"": 99.88,
        ""maxPricePerSquareFoot"": 2315.16,
        ""averageSquareFootage"": 2322,
        ""medianSquareFootage"": 2186,
        ""minSquareFootage"": 768,
        ""maxSquareFootage"": 6595,
        ""averageDaysOnMarket"": 57.77,
        ""medianDaysOnMarket"": 29,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 363,
        ""newListings"": 522,
        ""totalListings"": 1352,
        ""dataByPropertyType"": [
          {
            ""propertyType"": ""Land"",
            ""averagePrice"": 1340785,
            ""medianPrice"": 700000,
            ""minPrice"": 75000,
            ""maxPrice"": 5400000,
            ""averagePricePerSquareFoot"": null,
            ""medianPricePerSquareFoot"": null,
            ""minPricePerSquareFoot"": null,
            ""maxPricePerSquareFoot"": null,
            ""averageSquareFootage"": null,
            ""medianSquareFootage"": null,
            ""minSquareFootage"": null,
            ""maxSquareFootage"": null,
            ""averageDaysOnMarket"": 152.95,
            ""medianDaysOnMarket"": 152,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 334,
            ""newListings"": 3,
            ""totalListings"": 41
          },
          {
            ""propertyType"": ""Multi-Family"",
            ""averagePrice"": 430000,
            ""medianPrice"": 430000,
            ""minPrice"": 430000,
            ""maxPrice"": 430000,
            ""averagePricePerSquareFoot"": 204.37,
            ""medianPricePerSquareFoot"": 204.37,
            ""minPricePerSquareFoot"": 204.37,
            ""maxPricePerSquareFoot"": 204.37,
            ""averageSquareFootage"": 2104,
            ""medianSquareFootage"": 2104,
            ""minSquareFootage"": 2104,
            ""maxSquareFootage"": 2104,
            ""averageDaysOnMarket"": 7,
            ""medianDaysOnMarket"": 7,
            ""minDaysOnMarket"": 7,
            ""maxDaysOnMarket"": 7,
            ""newListings"": 1,
            ""totalListings"": 1
          },
          {
            ""propertyType"": ""Single Family"",
            ""averagePrice"": 441037,
            ""medianPrice"": 379970,
            ""minPrice"": 169000,
            ""maxPrice"": 4815525,
            ""averagePricePerSquareFoot"": 189.23,
            ""medianPricePerSquareFoot"": 181.96,
            ""minPricePerSquareFoot"": 99.88,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 2322,
            ""medianSquareFootage"": 2186,
            ""minSquareFootage"": 768,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 55.05,
            ""medianDaysOnMarket"": 27,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 363,
            ""newListings"": 518,
            ""totalListings"": 1310
          }
        ],
        ""dataByBedrooms"": [
          {
            ""bedrooms"": 1,
            ""averagePrice"": 888000,
            ""medianPrice"": 888000,
            ""minPrice"": 888000,
            ""maxPrice"": 888000,
            ""averagePricePerSquareFoot"": 911.7,
            ""medianPricePerSquareFoot"": 911.7,
            ""minPricePerSquareFoot"": 911.7,
            ""maxPricePerSquareFoot"": 911.7,
            ""averageSquareFootage"": 974,
            ""medianSquareFootage"": 974,
            ""minSquareFootage"": 974,
            ""maxSquareFootage"": 974,
            ""averageDaysOnMarket"": 158,
            ""medianDaysOnMarket"": 158,
            ""minDaysOnMarket"": 158,
            ""maxDaysOnMarket"": 158,
            ""newListings"": 0,
            ""totalListings"": 1
          },
          {
            ""bedrooms"": 2,
            ""averagePrice"": 361555,
            ""medianPrice"": 339900,
            ""minPrice"": 169000,
            ""maxPrice"": 635000,
            ""averagePricePerSquareFoot"": 218.07,
            ""medianPricePerSquareFoot"": 212.24,
            ""minPricePerSquareFoot"": 116.22,
            ""maxPricePerSquareFoot"": 343.75,
            ""averageSquareFootage"": 1702,
            ""medianSquareFootage"": 1571,
            ""minSquareFootage"": 768,
            ""maxSquareFootage"": 2917,
            ""averageDaysOnMarket"": 59.97,
            ""medianDaysOnMarket"": 33,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 247,
            ""newListings"": 12,
            ""totalListings"": 31
          },
          {
            ""bedrooms"": 3,
            ""averagePrice"": 346705,
            ""medianPrice"": 315000,
            ""minPrice"": 174900,
            ""maxPrice"": 4815525,
            ""averagePricePerSquareFoot"": 198.37,
            ""medianPricePerSquareFoot"": 190.93,
            ""minPricePerSquareFoot"": 115,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 1746,
            ""medianSquareFootage"": 1643,
            ""minSquareFootage"": 874,
            ""maxSquareFootage"": 3886,
            ""averageDaysOnMarket"": 51.04,
            ""medianDaysOnMarket"": 26,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 355,
            ""newListings"": 182,
            ""totalListings"": 476
          },
          {
            ""bedrooms"": 4,
            ""averagePrice"": 468320,
            ""medianPrice"": 410900,
            ""minPrice"": 226999,
            ""maxPrice"": 2850000,
            ""averagePricePerSquareFoot"": 181.61,
            ""medianPricePerSquareFoot"": 175.25,
            ""minPricePerSquareFoot"": 99.88,
            ""maxPricePerSquareFoot"": 724.45,
            ""averageSquareFootage"": 2540,
            ""medianSquareFootage"": 2426,
            ""minSquareFootage"": 1461,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 56.84,
            ""medianDaysOnMarket"": 30,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 363,
            ""newListings"": 261,
            ""totalListings"": 669
          },
          {
            ""bedrooms"": 5,
            ""averagePrice"": 645517,
            ""medianPrice"": 569900,
            ""minPrice"": 285000,
            ""maxPrice"": 4800000,
            ""averagePricePerSquareFoot"": 183.03,
            ""medianPricePerSquareFoot"": 168.98,
            ""minPricePerSquareFoot"": 114.3,
            ""maxPricePerSquareFoot"": 851.21,
            ""averageSquareFootage"": 3379,
            ""medianSquareFootage"": 3262,
            ""minSquareFootage"": 1766,
            ""maxSquareFootage"": 6203,
            ""averageDaysOnMarket"": 57.2,
            ""medianDaysOnMarket"": 20,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 304,
            ""newListings"": 61,
            ""totalListings"": 127
          },
          {
            ""bedrooms"": 6,
            ""averagePrice"": 824841,
            ""medianPrice"": 774000,
            ""minPrice"": 410000,
            ""maxPrice"": 1435000,
            ""averagePricePerSquareFoot"": 179.26,
            ""medianPricePerSquareFoot"": 179.69,
            ""minPricePerSquareFoot"": 125.77,
            ""maxPricePerSquareFoot"": 253.18,
            ""averageSquareFootage"": 4483,
            ""medianSquareFootage"": 4402,
            ""minSquareFootage"": 3260,
            ""maxSquareFootage"": 5668,
            ""averageDaysOnMarket"": 73.14,
            ""medianDaysOnMarket"": 14,
            ""minDaysOnMarket"": 5,
            ""maxDaysOnMarket"": 269,
            ""newListings"": 3,
            ""totalListings"": 7
          }
        ]
      },
      ""2026-04"": {
        ""date"": ""2026-04-01T00:00:00.000Z"",
        ""averagePrice"": 496772,
        ""medianPrice"": 384990,
        ""minPrice"": 69900,
        ""maxPrice"": 6200000,
        ""averagePricePerSquareFoot"": 192.72,
        ""medianPricePerSquareFoot"": 183.38,
        ""minPricePerSquareFoot"": 99.88,
        ""maxPricePerSquareFoot"": 2315.16,
        ""averageSquareFootage"": 2346,
        ""medianSquareFootage"": 2210,
        ""minSquareFootage"": 720,
        ""maxSquareFootage"": 6595,
        ""averageDaysOnMarket"": 57.78,
        ""medianDaysOnMarket"": 33,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 356,
        ""newListings"": 490,
        ""totalListings"": 1438,
        ""dataByPropertyType"": [
          {
            ""propertyType"": ""Land"",
            ""averagePrice"": 1659067,
            ""medianPrice"": 1230000,
            ""minPrice"": 69900,
            ""maxPrice"": 6200000,
            ""averagePricePerSquareFoot"": null,
            ""medianPricePerSquareFoot"": null,
            ""minPricePerSquareFoot"": null,
            ""maxPricePerSquareFoot"": null,
            ""averageSquareFootage"": null,
            ""medianSquareFootage"": null,
            ""minSquareFootage"": null,
            ""maxSquareFootage"": null,
            ""averageDaysOnMarket"": 148.75,
            ""medianDaysOnMarket"": 148,
            ""minDaysOnMarket"": 9,
            ""maxDaysOnMarket"": 356,
            ""newListings"": 8,
            ""totalListings"": 47
          },
          {
            ""propertyType"": ""Multi-Family"",
            ""averagePrice"": 715000,
            ""medianPrice"": 430000,
            ""minPrice"": 430000,
            ""maxPrice"": 1000000,
            ""averagePricePerSquareFoot"": 195.91,
            ""medianPricePerSquareFoot"": 187.44,
            ""minPricePerSquareFoot"": 187.44,
            ""maxPricePerSquareFoot"": 204.37,
            ""averageSquareFootage"": 3720,
            ""medianSquareFootage"": 2104,
            ""minSquareFootage"": 2104,
            ""maxSquareFootage"": 5335,
            ""averageDaysOnMarket"": 112,
            ""medianDaysOnMarket"": 29,
            ""minDaysOnMarket"": 29,
            ""maxDaysOnMarket"": 195,
            ""newListings"": 0,
            ""totalListings"": 2
          },
          {
            ""propertyType"": ""Single Family"",
            ""averagePrice"": 457129,
            ""medianPrice"": 382999,
            ""minPrice"": 169000,
            ""maxPrice"": 5890000,
            ""averagePricePerSquareFoot"": 192.72,
            ""medianPricePerSquareFoot"": 183.35,
            ""minPricePerSquareFoot"": 99.88,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 2344,
            ""medianSquareFootage"": 2210,
            ""minSquareFootage"": 720,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 54.8,
            ""medianDaysOnMarket"": 32,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 349,
            ""newListings"": 482,
            ""totalListings"": 1389
          }
        ],
        ""dataByBedrooms"": [
          {
            ""bedrooms"": 1,
            ""averagePrice"": 888000,
            ""medianPrice"": 888000,
            ""minPrice"": 888000,
            ""maxPrice"": 888000,
            ""averagePricePerSquareFoot"": 911.7,
            ""medianPricePerSquareFoot"": 911.7,
            ""minPricePerSquareFoot"": 911.7,
            ""maxPricePerSquareFoot"": 911.7,
            ""averageSquareFootage"": 974,
            ""medianSquareFootage"": 974,
            ""minSquareFootage"": 974,
            ""maxSquareFootage"": 974,
            ""averageDaysOnMarket"": 188,
            ""medianDaysOnMarket"": 188,
            ""minDaysOnMarket"": 188,
            ""maxDaysOnMarket"": 188,
            ""newListings"": 0,
            ""totalListings"": 1
          },
          {
            ""bedrooms"": 2,
            ""averagePrice"": 353206,
            ""medianPrice"": 327000,
            ""minPrice"": 169000,
            ""maxPrice"": 635000,
            ""averagePricePerSquareFoot"": 217.17,
            ""medianPricePerSquareFoot"": 213.13,
            ""minPricePerSquareFoot"": 112.1,
            ""maxPricePerSquareFoot"": 343.75,
            ""averageSquareFootage"": 1673,
            ""medianSquareFootage"": 1556,
            ""minSquareFootage"": 720,
            ""maxSquareFootage"": 2917,
            ""averageDaysOnMarket"": 65.97,
            ""medianDaysOnMarket"": 46,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 247,
            ""newListings"": 3,
            ""totalListings"": 32
          },
          {
            ""bedrooms"": 3,
            ""averagePrice"": 351781,
            ""medianPrice"": 317000,
            ""minPrice"": 174900,
            ""maxPrice"": 4815525,
            ""averagePricePerSquareFoot"": 200.49,
            ""medianPricePerSquareFoot"": 192.54,
            ""minPricePerSquareFoot"": 103.33,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 1752,
            ""medianSquareFootage"": 1667,
            ""minSquareFootage"": 874,
            ""maxSquareFootage"": 3886,
            ""averageDaysOnMarket"": 50.72,
            ""medianDaysOnMarket"": 29,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 328,
            ""newListings"": 164,
            ""totalListings"": 490
          },
          {
            ""bedrooms"": 4,
            ""averagePrice"": 492724,
            ""medianPrice"": 416000,
            ""minPrice"": 226999,
            ""maxPrice"": 5890000,
            ""averagePricePerSquareFoot"": 187.39,
            ""medianPricePerSquareFoot"": 176.15,
            ""minPricePerSquareFoot"": 99.88,
            ""maxPricePerSquareFoot"": 1370.72,
            ""averageSquareFootage"": 2554,
            ""medianSquareFootage"": 2457,
            ""minSquareFootage"": 1461,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 56.61,
            ""medianDaysOnMarket"": 32,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 349,
            ""newListings"": 259,
            ""totalListings"": 726
          },
          {
            ""bedrooms"": 5,
            ""averagePrice"": 656076,
            ""medianPrice"": 575000,
            ""minPrice"": 285000,
            ""maxPrice"": 4800000,
            ""averagePricePerSquareFoot"": 182.76,
            ""medianPricePerSquareFoot"": 168.98,
            ""minPricePerSquareFoot"": 106.38,
            ""maxPricePerSquareFoot"": 851.21,
            ""averageSquareFootage"": 3447,
            ""medianSquareFootage"": 3382,
            ""minSquareFootage"": 1766,
            ""maxSquareFootage"": 6203,
            ""averageDaysOnMarket"": 54.96,
            ""medianDaysOnMarket"": 26,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 328,
            ""newListings"": 56,
            ""totalListings"": 137
          },
          {
            ""bedrooms"": 6,
            ""averagePrice"": 843798,
            ""medianPrice"": 774000,
            ""minPrice"": 410000,
            ""maxPrice"": 1435000,
            ""averagePricePerSquareFoot"": 178.91,
            ""medianPricePerSquareFoot"": 187.44,
            ""minPricePerSquareFoot"": 125.77,
            ""maxPricePerSquareFoot"": 253.18,
            ""averageSquareFootage"": 4540,
            ""medianSquareFootage"": 4403,
            ""minSquareFootage"": 3260,
            ""maxSquareFootage"": 5668,
            ""averageDaysOnMarket"": 109.6,
            ""medianDaysOnMarket"": 132,
            ""minDaysOnMarket"": 43,
            ""maxDaysOnMarket"": 195,
            ""newListings"": 0,
            ""totalListings"": 5
          }
        ]
      },
      ""2026-05"": {
        ""date"": ""2026-05-01T00:00:00.000Z"",
        ""averagePrice"": 499904,
        ""medianPrice"": 385000,
        ""minPrice"": 61000,
        ""maxPrice"": 6200000,
        ""averagePricePerSquareFoot"": 192.17,
        ""medianPricePerSquareFoot"": 184.02,
        ""minPricePerSquareFoot"": 99.88,
        ""maxPricePerSquareFoot"": 2315.16,
        ""averageSquareFootage"": 2354,
        ""medianSquareFootage"": 2206,
        ""minSquareFootage"": 720,
        ""maxSquareFootage"": 6595,
        ""averageDaysOnMarket"": 58.68,
        ""medianDaysOnMarket"": 35,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 359,
        ""newListings"": 515,
        ""totalListings"": 1503,
        ""dataByPropertyType"": [
          {
            ""propertyType"": ""Land"",
            ""averagePrice"": 1684787,
            ""medianPrice"": 1125000,
            ""minPrice"": 61000,
            ""maxPrice"": 6200000,
            ""averagePricePerSquareFoot"": null,
            ""medianPricePerSquareFoot"": null,
            ""minPricePerSquareFoot"": null,
            ""maxPricePerSquareFoot"": null,
            ""averageSquareFootage"": null,
            ""medianSquareFootage"": null,
            ""minSquareFootage"": null,
            ""maxSquareFootage"": null,
            ""averageDaysOnMarket"": 139.5,
            ""medianDaysOnMarket"": 97,
            ""minDaysOnMarket"": 4,
            ""maxDaysOnMarket"": 356,
            ""newListings"": 9,
            ""totalListings"": 52
          },
          {
            ""propertyType"": ""Multi-Family"",
            ""averagePrice"": 430000,
            ""medianPrice"": 430000,
            ""minPrice"": 430000,
            ""maxPrice"": 430000,
            ""averagePricePerSquareFoot"": 204.37,
            ""medianPricePerSquareFoot"": 204.37,
            ""minPricePerSquareFoot"": 204.37,
            ""maxPricePerSquareFoot"": 204.37,
            ""averageSquareFootage"": 2104,
            ""medianSquareFootage"": 2104,
            ""minSquareFootage"": 2104,
            ""maxSquareFootage"": 2104,
            ""averageDaysOnMarket"": 29,
            ""medianDaysOnMarket"": 29,
            ""minDaysOnMarket"": 29,
            ""maxDaysOnMarket"": 29,
            ""newListings"": 0,
            ""totalListings"": 1
          },
          {
            ""propertyType"": ""Single Family"",
            ""averagePrice"": 459178,
            ""medianPrice"": 384999,
            ""minPrice"": 159000,
            ""maxPrice"": 5890000,
            ""averagePricePerSquareFoot"": 192.16,
            ""medianPricePerSquareFoot"": 183.68,
            ""minPricePerSquareFoot"": 99.88,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 2362,
            ""medianSquareFootage"": 2214,
            ""minSquareFootage"": 720,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 56.34,
            ""medianDaysOnMarket"": 34,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 359,
            ""newListings"": 496,
            ""totalListings"": 1432
          },
          {
            ""propertyType"": ""Townhouse"",
            ""averagePrice"": 320772,
            ""medianPrice"": 320000,
            ""minPrice"": 296000,
            ""maxPrice"": 340000,
            ""averagePricePerSquareFoot"": 192.08,
            ""medianPricePerSquareFoot"": 192.64,
            ""minPricePerSquareFoot"": 172.8,
            ""maxPricePerSquareFoot"": 203.54,
            ""averageSquareFootage"": 1671,
            ""medianSquareFootage"": 1713,
            ""minSquareFootage"": 1582,
            ""maxSquareFootage"": 1746,
            ""averageDaysOnMarket"": 30.22,
            ""medianDaysOnMarket"": 27,
            ""minDaysOnMarket"": 24,
            ""maxDaysOnMarket"": 42,
            ""newListings"": 10,
            ""totalListings"": 18
          }
        ],
        ""dataByBedrooms"": [
          {
            ""bedrooms"": 1,
            ""averagePrice"": 888000,
            ""medianPrice"": 888000,
            ""minPrice"": 888000,
            ""maxPrice"": 888000,
            ""averagePricePerSquareFoot"": 911.7,
            ""medianPricePerSquareFoot"": 911.7,
            ""minPricePerSquareFoot"": 911.7,
            ""maxPricePerSquareFoot"": 911.7,
            ""averageSquareFootage"": 974,
            ""medianSquareFootage"": 974,
            ""minSquareFootage"": 974,
            ""maxSquareFootage"": 974,
            ""averageDaysOnMarket"": 219,
            ""medianDaysOnMarket"": 219,
            ""minDaysOnMarket"": 219,
            ""maxDaysOnMarket"": 219,
            ""newListings"": 0,
            ""totalListings"": 1
          },
          {
            ""bedrooms"": 2,
            ""averagePrice"": 349422,
            ""medianPrice"": 327000,
            ""minPrice"": 159000,
            ""maxPrice"": 599000,
            ""averagePricePerSquareFoot"": 212.28,
            ""medianPricePerSquareFoot"": 204.37,
            ""minPricePerSquareFoot"": 112.1,
            ""maxPricePerSquareFoot"": 343.75,
            ""averageSquareFootage"": 1684,
            ""medianSquareFootage"": 1560,
            ""minSquareFootage"": 720,
            ""maxSquareFootage"": 2917,
            ""averageDaysOnMarket"": 69.12,
            ""medianDaysOnMarket"": 46,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 241,
            ""newListings"": 6,
            ""totalListings"": 32
          },
          {
            ""bedrooms"": 3,
            ""averagePrice"": 354129,
            ""medianPrice"": 320000,
            ""minPrice"": 165000,
            ""maxPrice"": 4815525,
            ""averagePricePerSquareFoot"": 199.61,
            ""medianPricePerSquareFoot"": 192.64,
            ""minPricePerSquareFoot"": 103.33,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 1773,
            ""medianSquareFootage"": 1688,
            ""minSquareFootage"": 1032,
            ""maxSquareFootage"": 3886,
            ""averageDaysOnMarket"": 54.78,
            ""medianDaysOnMarket"": 34,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 359,
            ""newListings"": 154,
            ""totalListings"": 499
          },
          {
            ""bedrooms"": 4,
            ""averagePrice"": 489097,
            ""medianPrice"": 409990,
            ""minPrice"": 254900,
            ""maxPrice"": 5890000,
            ""averagePricePerSquareFoot"": 187.4,
            ""medianPricePerSquareFoot"": 176.91,
            ""minPricePerSquareFoot"": 99.88,
            ""maxPricePerSquareFoot"": 1370.72,
            ""averageSquareFootage"": 2539,
            ""medianSquareFootage"": 2426,
            ""minSquareFootage"": 1461,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 56.43,
            ""medianDaysOnMarket"": 32,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 354,
            ""newListings"": 286,
            ""totalListings"": 767
          },
          {
            ""bedrooms"": 5,
            ""averagePrice"": 652352,
            ""medianPrice"": 575000,
            ""minPrice"": 285000,
            ""maxPrice"": 4800000,
            ""averagePricePerSquareFoot"": 183.12,
            ""medianPricePerSquareFoot"": 169.27,
            ""minPricePerSquareFoot"": 100.12,
            ""maxPricePerSquareFoot"": 851.21,
            ""averageSquareFootage"": 3443,
            ""medianSquareFootage"": 3429,
            ""minSquareFootage"": 1766,
            ""maxSquareFootage"": 5712,
            ""averageDaysOnMarket"": 52.9,
            ""medianDaysOnMarket"": 31,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 358,
            ""newListings"": 59,
            ""totalListings"": 147
          },
          {
            ""bedrooms"": 6,
            ""averagePrice"": 786798,
            ""medianPrice"": 725000,
            ""minPrice"": 400000,
            ""maxPrice"": 1435000,
            ""averagePricePerSquareFoot"": 173.56,
            ""medianPricePerSquareFoot"": 163.73,
            ""minPricePerSquareFoot"": 122.7,
            ""maxPricePerSquareFoot"": 253.18,
            ""averageSquareFootage"": 4358,
            ""medianSquareFootage"": 4403,
            ""minSquareFootage"": 3260,
            ""maxSquareFootage"": 5668,
            ""averageDaysOnMarket"": 84.6,
            ""medianDaysOnMarket"": 63,
            ""minDaysOnMarket"": 30,
            ""maxDaysOnMarket"": 146,
            ""newListings"": 1,
            ""totalListings"": 5
          }
        ]
      },
      ""2026-06"": {
        ""date"": ""2026-06-01T00:00:00.000Z"",
        ""averagePrice"": 508161,
        ""medianPrice"": 384990,
        ""minPrice"": 61000,
        ""maxPrice"": 8235000,
        ""averagePricePerSquareFoot"": 191.89,
        ""medianPricePerSquareFoot"": 183.89,
        ""minPricePerSquareFoot"": 99.88,
        ""maxPricePerSquareFoot"": 2315.16,
        ""averageSquareFootage"": 2342,
        ""medianSquareFootage"": 2186,
        ""minSquareFootage"": 720,
        ""maxSquareFootage"": 6595,
        ""averageDaysOnMarket"": 60.11,
        ""medianDaysOnMarket"": 36,
        ""minDaysOnMarket"": 1,
        ""maxDaysOnMarket"": 365,
        ""newListings"": 100,
        ""totalListings"": 1513,
        ""dataByPropertyType"": [
          {
            ""propertyType"": ""Land"",
            ""averagePrice"": 1836974,
            ""medianPrice"": 1375000,
            ""minPrice"": 61000,
            ""maxPrice"": 8235000,
            ""averagePricePerSquareFoot"": null,
            ""medianPricePerSquareFoot"": null,
            ""minPricePerSquareFoot"": null,
            ""maxPricePerSquareFoot"": null,
            ""averageSquareFootage"": null,
            ""medianSquareFootage"": null,
            ""minSquareFootage"": null,
            ""maxSquareFootage"": null,
            ""averageDaysOnMarket"": 134.36,
            ""medianDaysOnMarket"": 95,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 356,
            ""newListings"": 1,
            ""totalListings"": 59
          },
          {
            ""propertyType"": ""Manufactured"",
            ""averagePrice"": 4815525,
            ""medianPrice"": 4815525,
            ""minPrice"": 4815525,
            ""maxPrice"": 4815525,
            ""averagePricePerSquareFoot"": 2315.16,
            ""medianPricePerSquareFoot"": 2315.16,
            ""minPricePerSquareFoot"": 2315.16,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 2080,
            ""medianSquareFootage"": 2080,
            ""minSquareFootage"": 2080,
            ""maxSquareFootage"": 2080,
            ""averageDaysOnMarket"": 235,
            ""medianDaysOnMarket"": 235,
            ""minDaysOnMarket"": 235,
            ""maxDaysOnMarket"": 235,
            ""newListings"": 0,
            ""totalListings"": 1
          },
          {
            ""propertyType"": ""Multi-Family"",
            ""averagePrice"": 430000,
            ""medianPrice"": 430000,
            ""minPrice"": 430000,
            ""maxPrice"": 430000,
            ""averagePricePerSquareFoot"": 204.37,
            ""medianPricePerSquareFoot"": 204.37,
            ""minPricePerSquareFoot"": 204.37,
            ""maxPricePerSquareFoot"": 204.37,
            ""averageSquareFootage"": 2104,
            ""medianSquareFootage"": 2104,
            ""minSquareFootage"": 2104,
            ""maxSquareFootage"": 2104,
            ""averageDaysOnMarket"": 29,
            ""medianDaysOnMarket"": 29,
            ""minDaysOnMarket"": 29,
            ""maxDaysOnMarket"": 29,
            ""newListings"": 0,
            ""totalListings"": 1
          },
          {
            ""propertyType"": ""Single Family"",
            ""averagePrice"": 452882,
            ""medianPrice"": 383990,
            ""minPrice"": 159000,
            ""maxPrice"": 5890000,
            ""averagePricePerSquareFoot"": 190.41,
            ""medianPricePerSquareFoot"": 183.73,
            ""minPricePerSquareFoot"": 99.88,
            ""maxPricePerSquareFoot"": 1370.72,
            ""averageSquareFootage"": 2351,
            ""medianSquareFootage"": 2206,
            ""minSquareFootage"": 720,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 57.55,
            ""medianDaysOnMarket"": 36,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 365,
            ""newListings"": 99,
            ""totalListings"": 1434
          },
          {
            ""propertyType"": ""Townhouse"",
            ""averagePrice"": 321550,
            ""medianPrice"": 320000,
            ""minPrice"": 296000,
            ""maxPrice"": 340000,
            ""averagePricePerSquareFoot"": 191.54,
            ""medianPricePerSquareFoot"": 192.64,
            ""minPricePerSquareFoot"": 172.8,
            ""maxPricePerSquareFoot"": 203.54,
            ""averageSquareFootage"": 1680,
            ""medianSquareFootage"": 1713,
            ""minSquareFootage"": 1582,
            ""maxSquareFootage"": 1746,
            ""averageDaysOnMarket"": 36.67,
            ""medianDaysOnMarket"": 37,
            ""minDaysOnMarket"": 30,
            ""maxDaysOnMarket"": 46,
            ""newListings"": 0,
            ""totalListings"": 18
          }
        ],
        ""dataByBedrooms"": [
          {
            ""bedrooms"": 1,
            ""averagePrice"": 888000,
            ""medianPrice"": 888000,
            ""minPrice"": 888000,
            ""maxPrice"": 888000,
            ""averagePricePerSquareFoot"": 911.7,
            ""medianPricePerSquareFoot"": 911.7,
            ""minPricePerSquareFoot"": 911.7,
            ""maxPricePerSquareFoot"": 911.7,
            ""averageSquareFootage"": 974,
            ""medianSquareFootage"": 974,
            ""minSquareFootage"": 974,
            ""maxSquareFootage"": 974,
            ""averageDaysOnMarket"": 225,
            ""medianDaysOnMarket"": 225,
            ""minDaysOnMarket"": 225,
            ""maxDaysOnMarket"": 225,
            ""newListings"": 0,
            ""totalListings"": 1
          },
          {
            ""bedrooms"": 2,
            ""averagePrice"": 350532,
            ""medianPrice"": 339000,
            ""minPrice"": 159000,
            ""maxPrice"": 599000,
            ""averagePricePerSquareFoot"": 212.25,
            ""medianPricePerSquareFoot"": 204.37,
            ""minPricePerSquareFoot"": 112.1,
            ""maxPricePerSquareFoot"": 343.75,
            ""averageSquareFootage"": 1691,
            ""medianSquareFootage"": 1591,
            ""minSquareFootage"": 720,
            ""maxSquareFootage"": 2917,
            ""averageDaysOnMarket"": 74.68,
            ""medianDaysOnMarket"": 53,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 247,
            ""newListings"": 0,
            ""totalListings"": 31
          },
          {
            ""bedrooms"": 3,
            ""averagePrice"": 352168,
            ""medianPrice"": 320000,
            ""minPrice"": 165000,
            ""maxPrice"": 4815525,
            ""averagePricePerSquareFoot"": 199.39,
            ""medianPricePerSquareFoot"": 192.64,
            ""minPricePerSquareFoot"": 103.33,
            ""maxPricePerSquareFoot"": 2315.16,
            ""averageSquareFootage"": 1767,
            ""medianSquareFootage"": 1687,
            ""minSquareFootage"": 1032,
            ""maxSquareFootage"": 3886,
            ""averageDaysOnMarket"": 56.07,
            ""medianDaysOnMarket"": 36,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 365,
            ""newListings"": 35,
            ""totalListings"": 503
          },
          {
            ""bedrooms"": 4,
            ""averagePrice"": 486827,
            ""medianPrice"": 409990,
            ""minPrice"": 244999,
            ""maxPrice"": 5890000,
            ""averagePricePerSquareFoot"": 186.79,
            ""medianPricePerSquareFoot"": 177.38,
            ""minPricePerSquareFoot"": 99.88,
            ""maxPricePerSquareFoot"": 1370.72,
            ""averageSquareFootage"": 2539,
            ""medianSquareFootage"": 2426,
            ""minSquareFootage"": 1461,
            ""maxSquareFootage"": 6595,
            ""averageDaysOnMarket"": 57.3,
            ""medianDaysOnMarket"": 32,
            ""minDaysOnMarket"": 1,
            ""maxDaysOnMarket"": 353,
            ""newListings"": 54,
            ""totalListings"": 780
          },
          {
            ""bedrooms"": 5,
            ""averagePrice"": 656061,
            ""medianPrice"": 574000,
            ""minPrice"": 309900,
            ""maxPrice"": 4800000,
            ""averagePricePerSquareFoot"": 184,
            ""medianPricePerSquareFoot"": 168.56,
            ""minPricePerSquareFoot"": 100.12,
            ""maxPricePerSquareFoot"": 851.21,
            ""averageSquareFootage"": 3440,
            ""medianSquareFootage"": 3382,
            ""minSquareFootage"": 2152,
            ""maxSquareFootage"": 5712,
            ""averageDaysOnMarket"": 56.53,
            ""medianDaysOnMarket"": 33,
            ""minDaysOnMarket"": 2,
            ""maxDaysOnMarket"": 364,
            ""newListings"": 10,
            ""totalListings"": 134
          },
          {
            ""bedrooms"": 6,
            ""averagePrice"": 786798,
            ""medianPrice"": 725000,
            ""minPrice"": 400000,
            ""maxPrice"": 1435000,
            ""averagePricePerSquareFoot"": 173.56,
            ""medianPricePerSquareFoot"": 163.73,
            ""minPricePerSquareFoot"": 122.7,
            ""maxPricePerSquareFoot"": 253.18,
            ""averageSquareFootage"": 4358,
            ""medianSquareFootage"": 4403,
            ""minSquareFootage"": 3260,
            ""maxSquareFootage"": 5668,
            ""averageDaysOnMarket"": 85.8,
            ""medianDaysOnMarket"": 63,
            ""minDaysOnMarket"": 36,
            ""maxDaysOnMarket"": 146,
            ""newListings"": 0,
            ""totalListings"": 5
          }
        ]
      }
    }
  }
}";
    #endregion

}
